name: Eats Testes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs: 
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3.5.3

      - name: Install dependencies
        run: npm install

      - name: Run E2E testes Push
        run: npx cypress run  

 

      - name: Run E2E tests
        run: ${{ github.event.inputs.cli }}
